Added dockerfile, go.mod and go.sum to allow deployment via docker and automatic dependency downloads
PretendoNetwork/super-mario-maker pull request #2
Opened 2021-08-31 06:49 UTC by AnnoyingRain5

2021-08-31 10:47 UTC, mrjvs requested changes
Hey, thanks for the pr :)

Some changes are required before this can be merged:
 1. Comment your dockerfile, we need to know whats going on
 2. Use multistage, make one builder, one runner. so that we don't have unused files and dependencies after building, this will also improve runtime
 3. In the steps, install dependencies first, then copy the rest of the source for building
 4. don't use bullseye latest, use a static version of go.
 
 if you are unsure of how this works, read this tutorial: https://dev.to/karanpratapsingh/dockerize-your-go-app-46pp

2021-08-31 10:47 UTC, mrjvs commented on dockerfile
> +CMD ["go", "run", "."]
add a newline at end of file

2021-09-03 12:56 UTC, mrjvs approved these changes

2021-09-03 12:56 UTC, mrjvs commented
@jonbarrow dockerfile tested, all looks good and works properly

2025-02-05 19:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PretendoNetwork/super-mario-maker?pullRequest=2) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PretendoNetwork/super-mario-maker?pullRequest=2) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PretendoNetwork/super-mario-maker?pullRequest=2) it.</sub>

2025-02-20 23:09 UTC, binaryoverload commented
Thank you for this contribution - this was introduced in https://github.com/PretendoNetwork/super-mario-maker/pull/9 so I'll be closing this

2025-02-20 23:09 UTC, closed without merging